8 tela esqueci minha senha
fga-eps-mds/2023.1-Dnit-Front pull request #13
Opened 2023-05-29 15:20 UTC by CarolinaBarb

## [_Issue_ #8 ](link-para-issue)

 

## Descrição
Implementação da tela esqueci minha senha

## Imagens:
![Captura de tela 2023-05-26 225950](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/98655636/05af37b0-c47b-4e7a-8736-86ce8d406d24)
## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [x] Nova _feature_
- [ ] ...

## Lista de controle:

- [x] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-06-04 16:54 UTC, DenysRogeres requested changes
Vocês precisam conectar no endpoint de recuperar senha e enviar o e-mail por body params com o json com o email, tipo isso:
{
"email": "usuario@gmail.com"
}

O endpoint para recuperar senha é api/usuario/recuperarSenha

Se mantermos dessa forma, não vai estar conectado com o backend de usuario

2023-06-15 04:20 UTC, antoniotoineto commented
Olá @DenysRogeres 
Tô pegando essas pendências para podermos fechar esse PR
Implementei algumas coisas no front que precisávamos para poder enviar as informações para o back-end, mas empaquei em alguns pontos
Preciso da sua ajuda (ou de alguém que puder ajudar) para entender se o email está chegando no back ou não, analisando o endpoint que vc forneceu (api/usuario/recuperarSenha)
Acredito que estou perto de solucionar o problema mas preciso desses entendimentos para finalizar 👍

2023-06-15 04:28 UTC, antoniotoineto commented
Ah e só avisando que eu dei um merge dessa branch com a devel para poder testar algumas funcionalidades para poder desenvolver as pendências… e foi bom que já resolveu os conflitos

2023-06-15 22:57 UTC, antoniotoineto commented
Realizado as mudanças necessárias para enviar o link de recuperação para o e-mail indicado.
Coloquei os parâmetros no formato que a api /recuperarSenha espera, e agora o link é enviado corretamente após a integração com o front ✅

2023-06-15 23:00 UTC, lucas229 approved these changes
Aprovado!

2023-06-15 23:02 UTC, DenysRogeres approved these changes
Aprovado! Agora tá top

2023-06-15 23:03 UTC, merged