#9 implementando de Tela Recuperar Senha
fga-eps-mds/2023.1-Dnit-Front pull request #19
Opened 2023-05-30 14:19 UTC by LeticiaResende23

## Issue #9 

 

## Descrição
Implementação da tela recuperar senha

## Imagens:
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/89492943/50508d53-1b0e-4630-bcad-5fa02f3486d9)
## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [x] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [x] Atribui este pull request ao projeto
- [x] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-06-04 17:03 UTC, DenysRogeres requested changes
Deve-se realizar mudanças para conectar com o backend, a rota da pagina deve ser "redefinirSenha" e por query params estará o token que deverá ser pego e enviado para a rota do backend

2023-06-04 17:03 UTC, DenysRogeres commented on src/components/form/FormularioRecuperarSenha.tsx
Para essa tela funciona, vai ser enviado um link para o email do usuario com a seguinte url: https://dnit.vercel.app/redefinirSenha?token=1a3sdf1safasd4f56as4d6a4

Vocês devem deixar a tela pronta para pegar esse token e enviar junto com a nova senha para o endpoint /api/usuario/redefinirSenha (deve ser utilizado body params). Da seguinte forma:
{
  "senha": "novasenha",
  "uuidAutenticacao": "uuiQueEstaraNaUrlDaPagina"
}

Além disso, vocês devem validar se as senhas são iguais, isso já está acontecendo?

2023-06-07 02:43 UTC, Stain19 commented on src/components/form/FormularioRecuperarSenha.tsx
Acho que deveríamos atacar este problema nesta ou na próxima issue. Ficou definido alguma coisa na planning da sprint 4 em relação a isto?
Isso deveria passar por correção minha ou da Letícia?

2023-06-07 17:02 UTC, antoniotoineto commented on src/components/form/FormularioRecuperarSenha.tsx
Possivelmente isso vai ficar com algum integrante de EPS @Stain19

2023-06-15 23:06 UTC, isadoragalvaoss commented on src/App.tsx
> +      <Route path="/RecuperarSenha" element={<RecuperarSenha />} />
vamos seguir em camelCase, ajustado aqui

2023-06-16 19:32 UTC, antoniotoineto requested changes
Enxergo 2 pontos a serem melhorados/resolvidos:

1 - Testei a funcionalidade aqui na minha máquina e estou com algum problema... pois quando eu clico no link de recuperação de senha enviado ao meu email, vou para a página /home ou /login, mas não para a /recuperarSenha
Suspeito ser alguma gap na autenticação

2 - Alterar a URL da página para /redefinirSenha para não nos confundirmos

2023-06-16 19:32 UTC, antoniotoineto commented on src/App.tsx
> +      <Route path="/recuperarSenha" element={<ResetPassword />} />
Mudar o nome dessa rota para /redefinirSenha... para não nos confundirmos com a outra tela de recuperação de senha (a qual insere-se o email)

2023-06-17 03:09 UTC, isadoragalvaoss commented
@antoniotoineto Sobre os pontos que você trouxe na revisão:
-a rota não funcionou na sua maquina por que o link envia para o link do deploy e como a branch ainda não subiu, nessa rota não vai funcionar mesmo. Troca pra localhost que você vai conseguir testar
-alterei a rota

2023-06-17 03:11 UTC, antoniotoineto approved these changes
Certo @isadoragalvaoss obrigado... aprovado!

2023-06-17 03:14 UTC, DenysRogeres approved these changes
Muito bom, agora sim!

2023-06-17 03:15 UTC, merged