23 campo uf
fga-eps-mds/2023.1-Dnit-Front pull request #24
Opened 2023-06-01 02:45 UTC by isadoragalvaoss

## _Issue : #23 

Resolves fga-eps-mds/2023.1-Dnit-Front#23

## Descrição
Adição do campo select utilizando a rota de unidade federativa

## Imagens:
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54413452/0af6cba8-d450-4f83-8903-d52ebf757bb8)

## Tipo de alterações

- [x] _correção_ _de_ _bug_
- [ ] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [ ] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-06-01 04:17 UTC, DenysRogeres commented on src/components/form/FormularioCadastro.tsx
>            <Form.Item name="email" label="E-mail" rules={rules}>
Na reunião de segunda a Nayara pediu para mudar de "E-mail" para "E-mail Institucional". Além disso, como ajustes para próximas etapas, podemos adicionar uma validação para permitir cadastro apenas de pessoas que possuem e-mail institucional do DNIT ou da empresa terceirizada.

2023-06-01 04:26 UTC, DenysRogeres commented on src/components/form/FormularioCadastro.tsx
Vejo que há um certo problema de estilização nesse componente de cadastro. Quando ele carrega, a parte inferior fica muito próximo do final do "card". Além disso, a largura dele tá distoante em relação ao de login, há alguma forma de padronizar o tamanho? Ou ao menos diminuir a largura

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54676096/e75d02ba-bd85-4d7b-b4d0-988b5b5665fb)
tela de login para comparação:
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54676096/41de93b9-ae81-428e-8bb8-a25a498f3588)


Além disso, a imagem do campo não está centralizada
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54676096/33ac7834-3121-4f06-925e-36fad1a7b310)

2023-06-01 04:30 UTC, DenysRogeres commented on src/components/Button.tsx
Por algum motivo o botão de da página de login e da página de cadastro estão com tamanhos diferentes (altura)

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54676096/8fdf3bba-4bb2-49f9-89b2-3e5736cb49c8)

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54676096/4b8a043e-dbbc-46d6-9d19-db7af8278fc1)

Isso foi proposital? Caso tenha sido, não ficaria melhor padronizar, acredito que um botão com altura maior fique bom, assim como é na página do próprio gov br

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54676096/53cb4d5c-2748-4021-8472-15bf077644cd)

2023-06-01 04:34 UTC, DenysRogeres commented on src/components/form/FormularioCadastro.tsx
>    const [visible2, setVisible2] = useState(false);
Aqui vai só um ponto de obvervação. Estamos codando em portugues e em ingles, isso pode ficar um pouco confuso conforme a evolução do projeto, mas seria interessante definir nessa etapa inicial se vai ser tudo em portugues ou tudo em inglês. Óbvio que há itens que é pradrão do react e da linguagem, como o uso do hook useState vir sempre [nome, setNome], mas questões como: nome de função e variaveis talvez mereçam uma padronização para usar portugues ou usar tudo em ingles logo

2023-06-01 04:37 UTC, DenysRogeres commented on src/components/form/FormularioCadastro.tsx
> +                <Select
Como aqui há apenas uma empresa, poderíamos deixar o valor preenchido por default com o nome da empresa ou criar uma combo (mockada no front pois há apenas uma empresa) com o nome da empresa

2023-06-01 04:39 UTC, DenysRogeres requested changes
A combo esta funcionando, mas seria necessário corrigir o tamanho dos botões e o tamanho do card de login e cadastro para atualizarmos na main

2023-06-02 03:43 UTC, isadoragalvaoss commented on src/components/Button.tsx
Bom ponto!! Não tinha reparado nessa diferença na largura dos dois, arrumado!

2023-06-02 03:50 UTC, isadoragalvaoss commented on src/components/Button.tsx
Você falou a altura mas seria a largura, certo?

2023-06-02 04:32 UTC, isadoragalvaoss commented on src/components/form/FormularioCadastro.tsx
>    const [visible2, setVisible2] = useState(false);
Ótimo ponto!

2023-06-02 23:22 UTC, DenysRogeres approved these changes
Parabeeeens, ficou muito bom! Vamos pra cima que foguete não tem ré 🚀🚀🚀

2023-06-03 14:35 UTC, antoniotoineto commented
Fazendo merge dessa branch com a main, dada a devida aprovação dos revisores ✅

2023-06-03 14:36 UTC, merged