22 Validação de email e senha
fga-eps-mds/2023.1-Dnit-Front pull request #25
Opened 2023-06-01 03:54 UTC by antoniotoineto

## _Issue :_  Validação de email e senha 

Resolves fga-eps-mds/2023.1-Dnit-DOC#22

 

## Descrição
Implementa as validações necessárias indicadas na issue #22 :
- Verifica se o email é valido
- Verifica se a confirmação de senha é igual a senha

## Imagens:
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54555684/cc52ad73-f45f-434d-845f-977264f77466)

## Tipo de alterações

- [x] _correção_ _de_ _bug_
- [ ] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [x] Atribui este pull request ao projeto
- [x] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-06-01 04:50 UTC, DenysRogeres requested changes
Por qual motivo você está utilizando amarelo para mostrar que o e-mail é invalido?

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54676096/9479ed82-8a82-4017-9696-c11d17fb3196)

Essa cor não esta sendo "destacada" e fica difícil a leitura. Além disso, seria melhor utilizar uma regex para validar se o e-mail utilizado para fazer o cadastro de usuário é um e-mail institucional (com o domínio do DNIT). Um usuário que tem o email usuario@gmail.com não deveria poder fazer cadastro. O mesmo vale para a empresa, vale apenas verificar com o pessoal do DNIT como ficaria o domínio.

Último ponto: por qual motivo esse pull request tem como target  a branch main e não? É um hotfix? Caso seja um hotfix, é preciso realizar a descida para develop após o merge

Modifique apenas a cor da validação, deixando a cor vermelha e mude a label para "Email Institucional" (conforme a Nayara pediu) para que eu possa aprovar

2023-06-02 16:44 UTC, antoniotoineto commented
Certo, @DenysRogeres 
Obrigado pelas pontuações
Vou retirar a cor de laranja e deixar em vermelho
Farei a verificação para ser o email **@dnit.com** (caso o domínio seja diferente, podemos alterar depois... temos que falar com a Nayara sobre como são os emails institucionais do DNIT)
Sobre o email da empresa, temos que saber qual o nome da empresa e como são os emails institucionais desse também

2023-06-02 17:04 UTC, antoniotoineto commented
Alterações realizadas:

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54555684/b5eb2c04-27fa-478d-859b-4ca31f104a76)

Perguntei para a Nayara no Discord sobre o email institucional da empresa executora, vou aguardar ela responder e posso adicionar validação para o email da empresa também

2023-06-02 23:24 UTC, DenysRogeres approved these changes
Parabeeens, agora ficou top, muito bom!

2023-06-03 15:05 UTC, antoniotoineto commented
Valeu Denys 👍 
Estava só resolvendo os conflitos, agora vou merjar, dado sua aprovação

2023-06-03 15:07 UTC, merged