26 implementação da tela de listagem de escolas
fga-eps-mds/2023.1-Dnit-Front pull request #40
Opened 2023-06-17 21:42 UTC by JuliaSSouza

## _Issue : #26 

Resolves #26 

 

## Descrição
Implementação da tela de listagem de escolas
## Imagens:
![Tela1](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/88839152/329e45a9-6392-419d-90ee-ced36174aba4)
![Tela2_](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/88839152/1fb4e04b-a75c-40f2-8351-8101b726d856)

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [x] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [x] Atribui este pull request ao projeto
- [x] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-06-18 00:16 UTC, antoniotoineto requested changes
Acredito que faltam alguns pontos para aprovar o merge
1 - Integrar com back
2 - Colocar as informações das escolas na tela
3 - Esse PR deve ser redirecionado para a branch 'devel' e não 'main'

2023-06-18 01:53 UTC, antoniotoineto reviewed
Certo, agora está direcionada para a branch certa

2023-06-22 15:35 UTC, antoniotoineto approved these changes

2023-06-22 15:42 UTC, antoniotoineto requested changes
Requeri algumas mudanças
Caso precisem de ajuda pode entrar em contato comigo!! 👍

2023-06-22 15:42 UTC, antoniotoineto commented on src/components/components-escolasCadastradas/TabelaEscola.tsx
> +                          key={index}
Essa div da linha 192 está com nenhum estilização, e tá estranho quando ela aparece
Vamos ver se conseguimos algum className para ela ficar mais legal

2023-06-22 21:57 UTC, antoniotoineto commented
Ah é e tem mais dois pontos que esqueci de avisar:
1 - Vamos organizar essa pasta components-escolasCadastradas... criem uma pasta style dentro dela, e coloquem seus arquivos .css lá dentro.
2 - Vamos deixar o código em português mesmo, para ficar igual o back-end. Então o que vcs criaram agora de funções, arquivos e etc podem deixar em português.

2023-06-23 03:30 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/TabelaEscola.tsx
> +  const CloseModal = (id: number, index: number) => {
Essa função não esta sendo utilizada, ela pode ser removida daqui

2023-06-23 03:33 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/TabelaEscola.tsx
> +  const updateSchoolsPerPage = (value: number) => {
Essa função não esta sendo utilizada, ela pode ser removida daqui

2023-06-23 03:33 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/TabelaEscola.tsx
> +  const [isModalOpen, setIsModalOpen] = useState(false);
Essas variáveis também não estão sendo utilizadas, podem ser removidas

2023-06-23 03:35 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/TabelaEscola.tsx
> +      case 2:
Não tem nenhuma função quando for case 2? acho que não tem necessidade de usar switch case se só tem função pro case 1, da pra ser feito só com um if

2023-06-24 19:05 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/TabelaEscola.tsx
> +  /*const updateCurrentPage = (value: number) => {
Por que esta comentada? Se não ta utilizando não precisa deixar ai

2023-06-24 19:05 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/TabelaEscola.tsx
> +  /* const getSchool = async () => {
Mesma coisa, se não ta utilizando pode remover

2023-06-24 19:06 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +const ModalExibirInformacoes = (props: any) => {
Não é recomendado utilizar any no typescript, as variáveis devem ser tipadas

2023-06-24 19:07 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +  // console.log({ props });
Isso pode ser removido. Console.log é para teste em desenvolvimento, quando comitamos não devemos subir eles

2023-06-24 19:08 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +      console.log({ escola });
Memsa coisa, deve ser removido

2023-06-24 19:08 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +      console.log("Received values of form: ", selectedValue);
Removido também

2023-06-25 23:24 UTC, antoniotoineto approved these changes

2023-06-26 09:22 UTC, merged