17 alteracao de situacao de escolas
fga-eps-mds/2023.1-Dnit-Front pull request #44
Opened 2023-06-22 02:02 UTC by GuilhermeSoaress

## _Issue :_ Nome da issue

Resolves fga-eps-mds/2023.1-Dnit-Front#17

 

## Descrição
Tela para visualizar informações de escola.
## Imagens:
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/88786065/0a82a205-2dd1-434c-84e0-beaebaf878b3)
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/88786065/665650e2-08af-4565-acf9-49a53d8e02e1)

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [x] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [ ] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-06-22 16:13 UTC, antoniotoineto requested changes
Qualquer problema ou dúvida que tiverem, entrem em contato que podemos resolver isso juntos!

2023-06-22 16:13 UTC, antoniotoineto commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +                    <button className="br-button primary ml-2 " type="button" onClick={onFinish}>Salvar
Na minha tela, tive problemas com esses 3 botões: Excluir escola, Cancelar e Salvar
Acredito que é porque minha tela é um pouco menor então os botões não estavam na mesma linha
Isso é referente a configuração css, os tamanhos dos botões **br-button** estão em pixels e talvez isso possa interferir

2023-06-22 16:13 UTC, antoniotoineto commented on src/components/components-escolasCadastradas/ModalExcluirEscolas.tsx
> +            console.log(error);
Ao excluir a escola com sucesso (ou dando erro) temos que mostrar uma mensagem ao usuário (está nos critérios de aceitação então temos que fazer)
Isso pode ser feito com a importação do componente notification da biblioteca Ant Design... da uma olha nos formulário de Cadastro ou Login que usamos lá
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54555684/fd63b4c8-faaa-4442-aa84-76bbf2247ab6)

Ai dentro desse try catch colocamos um "api.sucess" em caso de sucesso ou "api.error" em caso de erro... dessa forma o usuário vai ser notificado do que aconteceu!
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54555684/b7c7d140-3c14-4dac-b624-59b9b5a88c98)

E por último, e não menos importante, se a escola foi excluída com sucesso, temos que fechar a modal de exclusão (isso já é feito) e temos que fechar a modal de exibição de informação das escola também! 
E, finalmente, pedir outra solicitação ao Banco de dados, para que a página seja atualizada, sem mostrar a escola excluída

2023-06-22 21:56 UTC, antoniotoineto commented
Ah é e tem mais dois pontos que esqueci de avisar:
1 - Vamos organizar essa pasta components-escolasCadastradas... criem uma pasta style dentro dela, e coloquem seus arquivos .css lá dentro.
2 - Vamos deixar o código em português mesmo, para ficar igual o back-end. Então o que vcs criaram agora de funções, arquivos e etc podem deixar em português.

2023-06-24 20:10 UTC, CarolinaBarb commented
Realizamos as alterações solicitadas

2023-06-25 18:11 UTC, antoniotoineto approved these changes

2023-06-25 18:12 UTC, antoniotoineto commented
Boa @CarolinaBarb e @GuilhermeSoaress 
Agora só precisamos dos testes e podemos merjar

2023-06-26 06:12 UTC, merged