7 importar planilha
fga-eps-mds/2023.1-Dnit-Front pull request #59
Opened 2023-07-03 04:10 UTC by avmricardo

## _Issue :_ Implementação da tela de importar planilhas

Resolves fga-eps-mds/2023.1-Dnit-Front#43

 

## Descrição
Arrumando as telas de importar planilhas de acordo com critérios do cliente.

## Imagens:
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/104032387/0b05d1a6-c116-496f-9804-42024e74efeb)
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/104032387/02c71853-6f46-4aec-9966-637163e34863)

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [ ] Nova _feature_
- [x] Outro: Implementando hotfix.
## Lista de controle:

- [x] Atribui este pull request ao projeto
- [x] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-07-05 03:56 UTC, antoniotoineto commented
Temos que dar uma olhada do porque não está passando no teste do sonar @ArturRSA19 @avmricardo

2023-07-05 14:55 UTC, isadoragalvaoss commented on src/components/form/Steps/Step3_Listagem.tsx
> +        <h2>Apenas as escolas abaixo foram adicionadas:</h2>
Troquem as mensagem nos testes também

2023-07-05 14:56 UTC, isadoragalvaoss commented
Façam as correções dos testes

2023-07-08 01:49 UTC, antoniotoineto commented
Adicionem esse arquivo release.yml abaixo dentro de .github -> workflows 
É para pegar as métricas do sonarcloud automaticamente

[release.zip](https://github.com/fga-eps-mds/2023.1-Dnit-Front/files/11987195/release.zip)

2023-07-08 04:20 UTC, isadoragalvaoss requested changes

2023-07-08 04:20 UTC, isadoragalvaoss commented on src/components/Upload/DragDrop.tsx
>            // Faça o que for necessário com a lista
Não há necessidade desses comentários

2023-07-08 04:20 UTC, isadoragalvaoss commented on src/components/Upload/DragDrop.tsx
>        } catch (error: any) {
Não usem any, tipem a variável

2023-07-09 16:03 UTC, isadoragalvaoss requested changes

2023-07-09 16:03 UTC, isadoragalvaoss commented on src/components/form/Steps/Step3_Listagem.tsx
>  //import Icone_aviso from "../../../assets/icons/iconeAviso.svg";
Se não esta sendo utilizado, pode remover

2023-07-09 16:03 UTC, isadoragalvaoss commented on src/components/form/Steps/Step3_erroTamanho.tsx
>  //import IconeErro from "../../../assets/icons/iconeErro.svg";
Mesma coisa, se não esta sendo utilizado, pode rremover

2023-07-09 16:03 UTC, isadoragalvaoss commented on src/components/form/Steps/Step3_erroTamanho.tsx
>  interface Step3_Erro2Props {
Tirar esse _ por que não deve ser declarado assim o nome, só letras e números

2023-07-09 18:52 UTC, isadoragalvaoss approved these changes

2023-07-09 18:53 UTC, merged