57 melhorias e hotfix na tela de informacoes da escola
fga-eps-mds/2023.1-Dnit-Front pull request #66
Opened 2023-07-07 03:11 UTC by GuilhermeSoaress

## _Issue : 57

Resolves fga-eps-mds/2023.1-Dnit-Front#57

 

## Descrição

Tela de exibir informações de uma escola com alterações solicitadas: modal mais larga para caber todos os campos e campos editáveis.
## Imagens:
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/88786065/a446c1a9-c6c1-466e-9d83-6d5c39e587ff)

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [ ] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [ ] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-07-07 21:35 UTC, antoniotoineto requested changes
Requisitado algumas mudanças

2023-07-07 21:35 UTC, antoniotoineto commented on src/context/Situation.tsx
> +  const [selectedValue, setSelectedValue] = useState('');
Podemos deixar o useState como valor padrão 0 mesmo, em vez de ''
Ai adicionamos uma situação com ID zero no banco, com a descrição "Sem situação" para indicar escolas sem situação.
É uma opção de contorno, mas podemos analisar se há alguma melhor

2023-07-07 21:35 UTC, antoniotoineto commented on src/components/components-escolasCadastradas/ModalBody.tsx
>  const ModalBody = (props: any) => {
E nessa Modal, por algum motivo os campos de Localização e Rede não aparecem nada, para nenhuma escola
Pode ser que seja forma que o Back esteja retornando, vamos verificar isso também

2023-07-07 21:35 UTC, antoniotoineto commented on src/components/components-escolasCadastradas/style/ModalExibirInformacoes.css
> +    position: fixed !important;
Temos a modal de confirmação de exclusão quebrada, eu suspeito ser devido a essa alteração no css. Tem que investigar também

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54555684/37fca7fe-279b-414e-ba49-b34c9b4a8c17)

2023-07-07 21:40 UTC, antoniotoineto commented
Vou dar uma olhada do porque não está realizando o deploy no sonar também, porque precisaremos dessas métricas

2023-07-08 01:50 UTC, antoniotoineto commented
Adicionem esse arquivo release.yml abaixo dentro de .github -> workflows 
É para pegar as métricas do sonarcloud automaticamente

[release.zip](https://github.com/fga-eps-mds/2023.1-Dnit-Front/files/11987195/release.zip)

2023-07-08 01:59 UTC, isadoragalvaoss requested changes

2023-07-08 01:59 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalBody.tsx
> +    console.log(event.target.value);
Não precisa ter console.log

2023-07-08 01:59 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalBody.tsx
>  const ModalBody = (props: any) => {
Não deve ser usado props, todos as props devem ser tipadas

2023-07-08 01:59 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalBody.tsx
> +          <div style={{ display: "flex", flexDirection: "row-reverse" }}>
Esse style tem que estar no arquivo css

2023-07-08 01:59 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +      console.log(alterarDadosEscolaData)
Não precisa de console.log

2023-07-08 01:59 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +        //api.error({ message: `Erro ao alterar dados` });
Se não está sendo utilizado, não tem porque estar aqui

2023-07-08 01:59 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +            //onUpdateSituacao={handleAlterarSituacao}
Mesma coisa, se não ta usando pode tirar

2023-07-08 02:01 UTC, isadoragalvaoss commented on src/consts/service.ts
> +const urlAPIEscolas = "https://localhost:7083/api";
Troca esse localhost pelo deploy

2023-07-08 02:13 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalBody.tsx
> +  const handleSituacaoChange = (event:any) => {
Não é recomendado usar any, esse e pros proximos event devem ser tipados

2023-07-08 02:50 UTC, isadoragalvaoss commented
Resolvam os conflitos dando um git pull na develop

2023-07-09 16:11 UTC, isadoragalvaoss requested changes

2023-07-09 16:11 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalBody.tsx
> +  const { Option } = Select;
Se não estiver utilizando, pode removerr

2023-07-09 16:11 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalBody.tsx
> +  const rules = [
Mesma coisa, se não ta utilizando, pode remover

2023-07-09 16:11 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +import etapasDeEnsino from "../../service/etapasDeEnsino";
Isso esta sendo utilizado?

2023-07-09 16:11 UTC, isadoragalvaoss commented on src/components/components-escolasCadastradas/ModalExibirInformacoes.tsx
> +    var id = 0;
Troca pra let ao inves de var

2023-07-10 04:52 UTC, antoniotoineto approved these changes

2023-07-10 04:52 UTC, merged