55 importacao de planilha de acidentes
fga-eps-mds/2023.1-Dnit-Front pull request #69
Opened 2023-07-08 21:29 UTC by lhuck4z

## _Issue :_ Nome da issue

Resolves fga-eps-mds/2023.1-Dnit-DOC#55

 

## Descrição

## Imagens:

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/108501120/3b54d080-8f0e-48e0-9407-89bc5dd5bc99)
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/108501120/fc037695-b446-4e09-82b5-393c716f8eaf)
![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/108501120/ddc3756d-1ea0-49fb-81ea-a7a7ea566614)

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [x] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [x] Atribui este pull request ao projeto
- [x] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [x] Adicionei testes para cobrir minhas alterações.
- [x] Todos os testes foram aprovados.

2023-07-08 21:42 UTC, isadoragalvaoss requested changes

2023-07-08 21:42 UTC, isadoragalvaoss commented on src/consts/service.ts
> +const SinistroUrl = `https://localhost:7083/api/sinistro/cadastrarSinistroPlanilha`;
Corrigir pra rota do deploy

2023-07-08 21:42 UTC, isadoragalvaoss commented on src/tests/ImportarPlanilhaSinistro.spec.tsx
> +        "https://localhost:7083/api/sinistro/cadastrarSinistroPlanilha",
Corrigir aqui nos testes também

2023-07-08 21:43 UTC, isadoragalvaoss commented
Façam um pull da develop pra corrigir os conflitos

2023-07-09 17:51 UTC, antoniotoineto requested changes
Temos algumas mensagens aparecendo em inglês, e precisamos tratar elas

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54555684/4fc27a77-bc8d-4058-a7e6-93e7641553b0)

2023-07-09 17:51 UTC, antoniotoineto commented on src/components/Upload/DragDropAcidentes.tsx
> +        <Button onClick={onClickBack} className="botaoCancelar" >
Essa div "container-botoes" tá no lugar errado, portanto está fora da modal

Movam essa div para o arquivo CadAcidentes.tsx para ficar dentro da modal (e também corrijam o nome do arquivo para CardAcidentes.tsx)

![image](https://github.com/fga-eps-mds/2023.1-Dnit-Front/assets/54555684/38d8755b-eefb-410f-98ea-829709a84090)

2023-07-09 21:43 UTC, antoniotoineto approved these changes

2023-07-09 22:02 UTC, isadoragalvaoss approved these changes

2023-07-09 22:02 UTC, merged